/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Registar;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class Registar_Produto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registar_Produto
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int idFornecedor, idProduto;

    public Registar_Produto() {
        initComponents();
        conexao = ModulodConexao.conector();
        consultar();
    }

    private void consultar() {
        String sql = "select * from tbFornecedor";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel modeloTb = (DefaultTableModel) tbleFornecedor.getModel();
            modeloTb.setNumRows(0);
            while (rs.next()) {
                modeloTb.addRow(new Object[]{rs.getString("nome"), rs.getString("decrisao"), rs.getString("bairro"), rs.getString("telefone")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void idFornecedor() {
        String sql = "select idFornecedor from tbFornecedor where nome=?";
        try {
            pst = conexao.prepareStatement(sql);
            int setar = tbleFornecedor.getSelectedRow();
            pst.setString(1, tbleFornecedor.getModel().getValueAt(setar, 0).toString());
            rs = pst.executeQuery();
            while (rs.next()) {
                idFornecedor = rs.getInt(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void idProduto() {
        String sql = "select idProduto from tbProduto where nome=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtProduto.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                idProduto = rs.getInt(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void pesquisarFornecedor() {
        String sql = "select * from tbFornecedor where nome like?";
        try {
            DefaultTableModel modeloTb = (DefaultTableModel) tbleFornecedor.getModel();
            modeloTb.setNumRows(0);
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "%" + txtPesquisar.getText() + "%");
            rs = pst.executeQuery();
            do {
                modeloTb.addRow(new Object[]{rs.getString("nome"), rs.getString("decrisao"), rs.getString("bairro"), rs.getString("telefone")});
            } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void stock() {
        String sql = "insert into tbStock(id_fornecedor,id_produto,data_entrega,quantidade) values(?,?,?,?)";
        try {
            String data = ((JTextField) jDateChooserData.getDateEditor().getUiComponent()).getText();
            pst = conexao.prepareStatement(sql);
            pst.setInt(1, idFornecedor);
            pst.setInt(2, idProduto);
            pst.setString(3, data);
            pst.setString(4, txtQuantidade.getText());
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                //JOptionPane.showMessageDialog(null, "Produto registado com sucesso!");
                txtProduto.setText("");
                txtQuantidade.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    private void registarProduto() {
        String sql = "insert into tbProduto(nome,preco) values(?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtProduto.getText());
            pst.setString(2, txtPreco.getText());
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                //JOptionPane.showMessageDialog(null, "Produto registado com sucesso!");
                //txtProduto.setText("");
                txtPreco.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbleFornecedor = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jSeparatorPesquisar = new javax.swing.JSeparator();
        txtProduto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistar = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblData = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        lblFormatoData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Registar produto");

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        tbleFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Bairro", "Descrisão dos serviços ", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbleFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbleFornecedor);

        txtPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisar.setText("Pesquisar fornecedor");
        txtPesquisar.setBorder(null);
        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusGained(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        txtProduto.setBorder(null);

        lblNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome.setText("* Nome do produto");

        lblPreco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPreco.setText("* Preço");

        txtPreco.setBorder(null);

        btnRegistar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistar.setText("Registar");
        btnRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQuantidade.setText("* Quantidade");

        txtQuantidade.setBorder(null);

        lblData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblData.setText("* Data de registo");

        jDateChooserData.setDateFormatString("yyyy-MM-dd");

        lblFormatoData.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblFormatoData.setText("(ano-MÊS-dia)");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Search.png"))); // NOI18N

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnelPrincipalLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPesquisar)
                                        .addComponent(jSeparatorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))))
                        .addGroup(pnelPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblQuantidade)
                                .addComponent(lblNome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProduto)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(138, 138, 138)
                                    .addComponent(lblPreco))
                                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblData)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPreco)
                                .addComponent(jSeparator2)
                                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFormatoData))
                                    .addGap(0, 98, Short.MAX_VALUE))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparatorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantidade)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormatoData)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        registarProduto();
        idProduto();
        stock();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void txtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusGained
        // TODO add your handling code here:
        txtPesquisar.setText("");
    }//GEN-LAST:event_txtPesquisarFocusGained

    private void tbleFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleFornecedorMouseClicked
        // TODO add your handling code here:
        idFornecedor();
    }//GEN-LAST:event_tbleFornecedorMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisarFornecedor();
    }//GEN-LAST:event_txtPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparatorPesquisar;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFormatoData;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JTable tbleFornecedor;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
