/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Painel_Login extends javax.swing.JFrame {

    /**
     * Creates new form Painel_Login
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Painel_Login() {
        initComponents();
        conexao = ModulodConexao.conector();
    }
    
        private void login() {
        String sql = "select*from tbGestor where nomeUsuario=? and senha=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNomeUsuario.getText());
            pst.setString(2, pwdUsuario.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String user = rs.getString(3);
                String pwd = rs.getString(4);
                if (user.equals(txtNomeUsuario.getText()) && pwd.equals(pwdUsuario.getText())) {
                    Painel_Principal principal = new Painel_Principal();
                    principal.setVisible(true);
                    this.dispose(); 
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha invalido(s)");
                txtNomeUsuario.setText("Nome do usuário");
                pwdUsuario.setText("*************");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        pnelLogin = new javax.swing.JPanel();
        txtNomeUsuario = new javax.swing.JTextField();
        pwdUsuario = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblVisualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnelPrincipal.setBackground(java.awt.SystemColor.textHighlight);

        lblLogin.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");

        pnelLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNomeUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeUsuario.setText("Nome do usuário");
        txtNomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeUsuarioFocusGained(evt);
            }
        });

        pwdUsuario.setText("jPasswordField1");
        pwdUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdUsuarioFocusGained(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Eye.png"))); // NOI18N
        lblVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVisualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnelLoginLayout = new javax.swing.GroupLayout(pnelLogin);
        pnelLogin.setLayout(pnelLoginLayout);
        pnelLoginLayout.setHorizontalGroup(
            pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelLoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addComponent(lblVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnelLoginLayout.setVerticalGroup(
            pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblVisualizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdUsuarioFocusGained
        // TODO add your handling code here:
        pwdUsuario.setText("");
        pwdUsuario.setEchoChar(('*'));
    }//GEN-LAST:event_pwdUsuarioFocusGained

    private void txtNomeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeUsuarioFocusGained
        // TODO add your handling code here:
        txtNomeUsuario.setText("");
    }//GEN-LAST:event_txtNomeUsuarioFocusGained

    private void lblVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualizarMouseClicked
        // TODO add your handling code here:
        pwdUsuario.setEchoChar((char) 0);
    }//GEN-LAST:event_lblVisualizarMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblVisualizar;
    private javax.swing.JPanel pnelLogin;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JPasswordField pwdUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
