/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.AtualizarDados.AtualizarDados_Fornecedor;
import View.AtualizarDados.AtualizarDados_Produto;
import View.AtualizarDados.AtualizarDados_Trabalhador;
import View.Consultar.Consultar_Fornecedor;
import View.Consultar.Consultar_Produto;
import View.Consultar.Consultar_Stock;
import View.Consultar.Consultar_Trabalhador;
import View.Registar.Registar_Produto;
import View.Registar.Registar_Fornecedor;
import View.Registar.Registar_Trabalhador;
import java.awt.Color;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class Painel_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Painel_Principal
     */
    Painel_Home home;

    public Painel_Principal() {
        initComponents();
        home = new Painel_Home();
        home.setVisible(true);
        jDesktopPaneCarregarPaineis.add(home);
    }

    private void setColor(JMenu menu) {
        menu.setForeground(new java.awt.Color(0, 153, 153));
    }

    private void resetColor(JMenu menu) {
        menu.setForeground(new java.awt.Color(0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        pnelCarregarPaineis = new javax.swing.JPanel();
        jDesktopPaneCarregarPaineis = new javax.swing.JDesktopPane();
        baradMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenu();
        registarProduto = new javax.swing.JMenuItem();
        consultarProduto = new javax.swing.JMenuItem();
        atualizarDadosProduto = new javax.swing.JMenuItem();
        removerProduto = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        registarFornecedor = new javax.swing.JMenuItem();
        consultarFornecedor = new javax.swing.JMenuItem();
        atualizarDadosFornecedor = new javax.swing.JMenuItem();
        removerFornecedor = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        consultarStock = new javax.swing.JMenuItem();
        menuTrabalhador = new javax.swing.JMenu();
        registarTrabalhador = new javax.swing.JMenuItem();
        consultarTrabalhador = new javax.swing.JMenuItem();
        atualizarDadosTrabalhador = new javax.swing.JMenuItem();
        removerTrabalhador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnelCarregarPaineis.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneCarregarPaineisLayout = new javax.swing.GroupLayout(jDesktopPaneCarregarPaineis);
        jDesktopPaneCarregarPaineis.setLayout(jDesktopPaneCarregarPaineisLayout);
        jDesktopPaneCarregarPaineisLayout.setHorizontalGroup(
            jDesktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jDesktopPaneCarregarPaineisLayout.setVerticalGroup(
            jDesktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnelCarregarPaineisLayout = new javax.swing.GroupLayout(pnelCarregarPaineis);
        pnelCarregarPaineis.setLayout(pnelCarregarPaineisLayout);
        pnelCarregarPaineisLayout.setHorizontalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCarregarPaineis)
        );
        pnelCarregarPaineisLayout.setVerticalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCarregarPaineis)
        );

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelCarregarPaineis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelCarregarPaineis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        baradMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        baradMenu.setPreferredSize(new java.awt.Dimension(56, 40));

        menuInicio.setForeground(new java.awt.Color(0, 153, 153));
        menuInicio.setText("Inicio");
        menuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuInicio.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        baradMenu.add(menuInicio);

        menuProduto.setText("Produto");
        menuProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProduto.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        registarProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registarProduto.setText("Registar");
        registarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(registarProduto);

        consultarProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarProduto.setText("Consultar");
        consultarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(consultarProduto);

        atualizarDadosProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        atualizarDadosProduto.setText("Atualizar dados");
        atualizarDadosProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarDadosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarDadosProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(atualizarDadosProduto);

        removerProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removerProduto.setText("Remover");
        removerProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProduto.add(removerProduto);

        baradMenu.add(menuProduto);

        menuFornecedor.setText("Fornecedor");
        menuFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFornecedor.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        registarFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registarFornecedor.setText("Registar");
        registarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(registarFornecedor);

        consultarFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarFornecedor.setText("Consultar");
        consultarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(consultarFornecedor);

        atualizarDadosFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        atualizarDadosFornecedor.setText("Atualizar dados");
        atualizarDadosFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarDadosFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarDadosFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(atualizarDadosFornecedor);

        removerFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removerFornecedor.setText("Remover");
        removerFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFornecedor.add(removerFornecedor);

        baradMenu.add(menuFornecedor);

        menuStock.setText("Stock");
        menuStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuStock.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        consultarStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarStock.setText("Consultar");
        consultarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarStockActionPerformed(evt);
            }
        });
        menuStock.add(consultarStock);

        baradMenu.add(menuStock);

        menuTrabalhador.setText("Trabalhador");
        menuTrabalhador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTrabalhador.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        registarTrabalhador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registarTrabalhador.setText("Registar");
        registarTrabalhador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registarTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarTrabalhadorActionPerformed(evt);
            }
        });
        menuTrabalhador.add(registarTrabalhador);

        consultarTrabalhador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarTrabalhador.setText("Consultar");
        consultarTrabalhador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTrabalhadorActionPerformed(evt);
            }
        });
        menuTrabalhador.add(consultarTrabalhador);

        atualizarDadosTrabalhador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        atualizarDadosTrabalhador.setText("Atualizar dados");
        atualizarDadosTrabalhador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarDadosTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarDadosTrabalhadorActionPerformed(evt);
            }
        });
        menuTrabalhador.add(atualizarDadosTrabalhador);

        removerTrabalhador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removerTrabalhador.setText("Remover");
        removerTrabalhador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTrabalhador.add(removerTrabalhador);

        baradMenu.add(menuTrabalhador);

        setJMenuBar(baradMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarProdutoActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        setColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Registar_Produto registar_produto = new Registar_Produto();
        registar_produto.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(registar_produto);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(registar_produto);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_registarProdutoActionPerformed

    private void registarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarFornecedorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        setColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Registar_Fornecedor registar_fornecedor = new Registar_Fornecedor();
        registar_fornecedor.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(registar_fornecedor);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(registar_fornecedor);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_registarFornecedorActionPerformed

    private void registarTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarTrabalhadorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        setColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Registar_Trabalhador registar_trabalhador = new Registar_Trabalhador();
        registar_trabalhador.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(registar_trabalhador);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(registar_trabalhador);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_registarTrabalhadorActionPerformed

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        // TODO add your handling code here:
        setColor(menuInicio);
        resetColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Painel_Home home = new Painel_Home();
        home.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(home);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(home);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_menuInicioMouseClicked

    private void consultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProdutoActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        setColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Consultar_Produto consultar_produto = new Consultar_Produto();
        consultar_produto.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(consultar_produto);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(consultar_produto);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_consultarProdutoActionPerformed

    private void consultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFornecedorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        setColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Consultar_Fornecedor consultar_fornecedor = new Consultar_Fornecedor();
        consultar_fornecedor.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(consultar_fornecedor);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(consultar_fornecedor);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_consultarFornecedorActionPerformed

    private void consultarTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTrabalhadorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        setColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Consultar_Trabalhador consultar_trabalhador = new Consultar_Trabalhador();
        consultar_trabalhador.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(consultar_trabalhador);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(consultar_trabalhador);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_consultarTrabalhadorActionPerformed

    private void atualizarDadosProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarDadosProdutoActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        setColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        AtualizarDados_Produto atualizarDados_produto = new AtualizarDados_Produto();
        atualizarDados_produto.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(atualizarDados_produto);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(atualizarDados_produto);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_atualizarDadosProdutoActionPerformed

    private void atualizarDadosFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarDadosFornecedorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        setColor(menuFornecedor);
        resetColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        AtualizarDados_Fornecedor atualizarDados_fornecedor = new AtualizarDados_Fornecedor();
        atualizarDados_fornecedor.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(atualizarDados_fornecedor);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(atualizarDados_fornecedor);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_atualizarDadosFornecedorActionPerformed

    private void atualizarDadosTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarDadosTrabalhadorActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        resetColor(menuFornecedor);
        resetColor(menuStock);
        setColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        AtualizarDados_Trabalhador atualizarDados_trabalhador = new AtualizarDados_Trabalhador();
        atualizarDados_trabalhador.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(atualizarDados_trabalhador);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(atualizarDados_trabalhador);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_atualizarDadosTrabalhadorActionPerformed

    private void consultarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarStockActionPerformed
        // TODO add your handling code here:
        resetColor(menuInicio);
        resetColor(menuProduto);
        resetColor(menuFornecedor);
        setColor(menuStock);
        resetColor(menuTrabalhador);
        jDesktopPaneCarregarPaineis.show();
        Consultar_Stock consultar_stock = new Consultar_Stock();
        consultar_stock.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(consultar_stock);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(consultar_stock);
            revalidate();
            repaint();
        }

    }//GEN-LAST:event_consultarStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atualizarDadosFornecedor;
    private javax.swing.JMenuItem atualizarDadosProduto;
    private javax.swing.JMenuItem atualizarDadosTrabalhador;
    private javax.swing.JMenuBar baradMenu;
    private javax.swing.JMenuItem consultarFornecedor;
    private javax.swing.JMenuItem consultarProduto;
    private javax.swing.JMenuItem consultarStock;
    private javax.swing.JMenuItem consultarTrabalhador;
    private javax.swing.JDesktopPane jDesktopPaneCarregarPaineis;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenu menuTrabalhador;
    private javax.swing.JPanel pnelCarregarPaineis;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JMenuItem registarFornecedor;
    private javax.swing.JMenuItem registarProduto;
    private javax.swing.JMenuItem registarTrabalhador;
    private javax.swing.JMenuItem removerFornecedor;
    private javax.swing.JMenuItem removerProduto;
    private javax.swing.JMenuItem removerTrabalhador;
    // End of variables declaration//GEN-END:variables
}
